# Generated by Django 5.2.4 on 2025-07-18 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GBVReport',
            fields=[
                ('name', models.CharField(help_text='Full name of the reporter', max_length=255)),
                ('email', models.EmailField(help_text='Email address for contact', max_length=254)),
                ('phone', models.CharField(help_text='Phone number for contact', max_length=20)),
                ('incident_date', models.DateTimeField(default=datetime.datetime(2025, 7, 18, 8, 40, 48, 466439))),
                ('incident_location', models.CharField(help_text='Location where the incident occurred', max_length=255)),
                ('incident_type', models.CharField(choices=[('physical', 'Physical Violence'), ('sexual', 'Sexual Violence'), ('emotional', 'Emotional/Psychological'), ('economic', 'Economic Violence'), ('other', 'Other')], default='physical', help_text='Type of incident reported', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the incident')),
                ('immediate_danger', models.BooleanField(default=False, help_text='Indicates if the reporter is in immediate danger')),
                ('needs_medical_attention', models.BooleanField(default=False, help_text='Indicates if the reporter needs medical attention')),
                ('reference_code', models.CharField(blank=True, help_text='Unique reference code for tracking the report', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'GBV Report',
                'verbose_name_plural': 'GBV Reports',
                'ordering': ['-date_reported'],
            },
        ),
    ]
