# Generated by Django 5.2.4 on 2025-07-18 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbvreport',
            name='incident_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 8, 58, 12, 173262)),
        ),
    ]
