# Generated by Django 5.2.4 on 2025-07-23 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_gbvreport_incident_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbvreport',
            name='incident_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 14, 33, 28, 541482)),
        ),
    ]
