# Generated by Django 5.1.3 on 2025-08-22 07:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_gbvreport_incident_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gbvreport',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gbvreport',
            name='reporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gbvreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='gbvreport',
            name='incident_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 9, 59, 56, 836172)),
        ),
        migrations.AlterField(
            model_name='gbvreport',
            name='incident_type',
            field=models.CharField(choices=[('physical', 'Physical Violence'), ('sexual', 'Sexual Violence'), ('emotional', 'Emotional/Psychological'), ('online', 'Online Bullying'), ('other', 'Other')], default='physical', help_text='Type of incident reported', max_length=20),
        ),
    ]
