# Generated by Django 5.2.4 on 2025-08-24 16:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_gbvreport_assigned_to_alter_gbvreport_incident_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gbvreport',
            name='email',
        ),
        migrations.RemoveField(
            model_name='gbvreport',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gbvreport',
            name='phone',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_pro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caseassignment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reports', to='reports.gbvreport'),
        ),
        migrations.AlterField(
            model_name='gbvreport',
            name='incident_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 24, 19, 20, 6, 181317)),
        ),
    ]
