# Generated by Django 5.2.4 on 2025-08-24 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_remove_gbvreport_email_remove_gbvreport_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbvreport',
            name='incident_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 24, 21, 33, 22, 715843)),
        ),
    ]
