# Generated by Django 5.2.4 on 2025-09-02 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_gbvreport_incident_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbvreport',
            name='incident_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 2, 20, 45, 34, 705743)),
        ),
    ]
